
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Add_Victim extends javax.swing.JFrame {

    /**
     * Creates new form Criminal
     */
    public Add_Victim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Victim_ID = new javax.swing.JLabel();
        Victim_Name = new javax.swing.JLabel();
        Victim_Contact = new javax.swing.JLabel();
        Victim_ID_Field = new javax.swing.JTextField();
        Victim_Name_Field = new javax.swing.JTextField();
        Victim_Contact_Field = new javax.swing.JTextField();
        Victim_Insert_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Victim_Address = new javax.swing.JLabel();
        Victim_Address_Field = new javax.swing.JTextField();
        Victim_FIR_ID = new javax.swing.JLabel();
        Victim_FIR_ID_Field = new javax.swing.JTextField();
        Victim_Gender = new javax.swing.JLabel();
        Victim_Gender_Field = new javax.swing.JTextField();
        Victim_Gender_ComboBox = new javax.swing.JComboBox<>();
        Victim_Return_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Victim_ID.setText("Victim_ID");

        Victim_Name.setText("Victim_Name");

        Victim_Contact.setText("Contact");

        Victim_ID_Field.setToolTipText("");
        Victim_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_ID_FieldActionPerformed(evt);
            }
        });

        Victim_Contact_Field.setToolTipText("");
        Victim_Contact_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_Contact_FieldActionPerformed(evt);
            }
        });

        Victim_Insert_Button.setText("Insert");
        Victim_Insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_Insert_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VICTIM FORM");

        Victim_Address.setText("Address");

        Victim_Address_Field.setToolTipText("");
        Victim_Address_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_Address_FieldActionPerformed(evt);
            }
        });

        Victim_FIR_ID.setText("FIR_ID");

        Victim_FIR_ID_Field.setToolTipText("");
        Victim_FIR_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_FIR_ID_FieldActionPerformed(evt);
            }
        });

        Victim_Gender.setText("Gender");

        Victim_Gender_Field.setEditable(false);
        Victim_Gender_Field.setText("Male");
        Victim_Gender_Field.setToolTipText("");
        Victim_Gender_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_Gender_FieldActionPerformed(evt);
            }
        });

        Victim_Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Victim_Gender_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_Gender_ComboBoxActionPerformed(evt);
            }
        });

        Victim_Return_Button.setText("Return");
        Victim_Return_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Victim_Return_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Victim_Address, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Victim_Gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Victim_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Victim_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(Victim_Contact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Victim_Address_Field)
                            .addComponent(Victim_Gender_Field)
                            .addComponent(Victim_Name_Field)
                            .addComponent(Victim_Contact_Field)
                            .addComponent(Victim_ID_Field, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Victim_FIR_ID)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Victim_FIR_ID_Field)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Victim_Insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Victim_Return_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(Victim_Gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Victim_ID)
                    .addComponent(Victim_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Victim_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Victim_Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Victim_Gender_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Victim_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Victim_Gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Victim_Address_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Victim_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Victim_Contact)
                    .addComponent(Victim_Contact_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Victim_FIR_ID)
                    .addComponent(Victim_FIR_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Victim_Insert_Button)
                    .addComponent(Victim_Return_Button))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String url="jdbc:sqlserver://localhost:1433;databaseName=CrimeRecordManagementSystem;user=MurtazaDatabase;password=murtaza123";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
       
    private void Victim_Insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_Insert_ButtonActionPerformed
        
        try
        {
            
             if(Victim_Address_Field.getText().trim().isEmpty() || 
               Victim_Contact_Field.getText().trim().isEmpty() ||  
               Victim_FIR_ID_Field.getText().trim().isEmpty() || 
               Victim_Gender_Field.getText().trim().isEmpty() ||
               Victim_ID_Field.getText().trim().isEmpty() ||
               Victim_Name_Field.getText().trim().isEmpty()      )
            {
                JOptionPane.showMessageDialog(this, "Fields Should Not Be Null");
            }

            else
            {
                Class.forName(driver);
                Connection connection= DriverManager.getConnection(url);

                String SQL="insert into Victim"
                        + "(Victim_name, Victim_name, Gender, victim_address, Victim_ph, Fir_id)"
                        +"values(?, ?, ?, ?, ?, ?)";

                PreparedStatement pst = connection.prepareStatement(SQL);

                pst.setString(1, Victim_ID_Field.getText());
                pst.setString(2, Victim_Name_Field.getText());
                pst.setString(3, Victim_Gender_Field.getText());
                pst.setString(4, Victim_Address_Field.getText());
                pst.setString(5, Victim_Contact_Field.getText());
                pst.setString(6, Victim_FIR_ID_Field.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Victim Details Insert Successfully");
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }
        
        
        
        
    }//GEN-LAST:event_Victim_Insert_ButtonActionPerformed

    private void Victim_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Victim_ID_FieldActionPerformed

    private void Victim_Contact_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_Contact_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Victim_Contact_FieldActionPerformed

    private void Victim_Address_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_Address_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Victim_Address_FieldActionPerformed

    private void Victim_FIR_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_FIR_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Victim_FIR_ID_FieldActionPerformed

    private void Victim_Gender_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_Gender_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Victim_Gender_FieldActionPerformed

    private void Victim_Gender_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_Gender_ComboBoxActionPerformed
        Victim_Gender_Field.setText(Victim_Gender_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_Victim_Gender_ComboBoxActionPerformed

    private void Victim_Return_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Victim_Return_ButtonActionPerformed
       Main_Page main_page = new Main_Page();
       main_page.setVisible(true);
       
        setVisible(false);
    }//GEN-LAST:event_Victim_Return_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Victim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Victim_Address;
    private javax.swing.JTextField Victim_Address_Field;
    private javax.swing.JLabel Victim_Contact;
    private javax.swing.JTextField Victim_Contact_Field;
    private javax.swing.JLabel Victim_FIR_ID;
    private javax.swing.JTextField Victim_FIR_ID_Field;
    private javax.swing.JLabel Victim_Gender;
    private javax.swing.JComboBox<String> Victim_Gender_ComboBox;
    private javax.swing.JTextField Victim_Gender_Field;
    private javax.swing.JLabel Victim_ID;
    private javax.swing.JTextField Victim_ID_Field;
    private javax.swing.JButton Victim_Insert_Button;
    private javax.swing.JLabel Victim_Name;
    private javax.swing.JTextField Victim_Name_Field;
    private javax.swing.JButton Victim_Return_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
