
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Court_Decision extends javax.swing.JFrame {

    /**
     * Creates new form Criminal
     */
    public Court_Decision() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Decision_Criminal_ID = new javax.swing.JLabel();
        Decision_Status = new javax.swing.JLabel();
        Decision_Section_Of_Law = new javax.swing.JLabel();
        Decision_Details = new javax.swing.JLabel();
        Decision_Criminal_ID_Field = new javax.swing.JTextField();
        Decision_Status_Field = new javax.swing.JTextField();
        Decision_Section_Of_Law_Field = new javax.swing.JTextField();
        Decision_Details_Field = new javax.swing.JTextField();
        Decision_Insert_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Decision_Status_ComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Decision_Criminal_ID.setText("Criminal ID");

        Decision_Status.setText("Status");

        Decision_Section_Of_Law.setText("Section_Of_Law");

        Decision_Details.setText("Details");

        Decision_Criminal_ID_Field.setToolTipText("yyyy-mm-dd");
        Decision_Criminal_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decision_Criminal_ID_FieldActionPerformed(evt);
            }
        });

        Decision_Status_Field.setEditable(false);
        Decision_Status_Field.setText("Pending");

        Decision_Section_Of_Law_Field.setToolTipText("int");
        Decision_Section_Of_Law_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decision_Section_Of_Law_FieldActionPerformed(evt);
            }
        });

        Decision_Insert_Button.setText("Insert");
        Decision_Insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decision_Insert_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COURT DECISION FORM");

        Decision_Status_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Solved", "Closed" }));
        Decision_Status_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decision_Status_ComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Decision_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Decision_Criminal_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(Decision_Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Decision_Section_Of_Law, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(Decision_Insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Decision_Criminal_ID_Field, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Decision_Status_Field))
                                        .addGap(12, 12, 12)))
                                .addComponent(Decision_Status_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Decision_Section_Of_Law_Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(Decision_Details_Field, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Decision_Criminal_ID)
                    .addComponent(Decision_Criminal_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Decision_Status)
                    .addComponent(Decision_Status_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Decision_Status_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Decision_Section_Of_Law)
                    .addComponent(Decision_Section_Of_Law_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Decision_Details)
                    .addComponent(Decision_Details_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Decision_Insert_Button)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String url="jdbc:sqlserver://localhost:1433;databaseName=CrimeRecordManagementSystem;user=MurtazaDatabase;password=murtaza123";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
       
    private void Decision_Insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decision_Insert_ButtonActionPerformed
        
        try
        {
            if(Decision_Criminal_ID_Field.getText().trim().isEmpty() || 
               Decision_Details_Field.getText().trim().isEmpty() ||  
               Decision_Section_Of_Law_Field.getText().trim().isEmpty() || 
               Decision_Status_Field.getText().trim().isEmpty() )
            {
                JOptionPane.showMessageDialog(this, "Fields Should Not Be Null");
               
            }

            else
            {
            
                Class.forName(driver);
                Connection connection= DriverManager.getConnection(url);

                String SQL="insert into Decision"
                        + "(Criminal_Id, Status, Section_of_law, Details)"
                        +"values(?, ?, ?, ?)";

                PreparedStatement pst = connection.prepareStatement(SQL);

                pst.setString(1, Decision_Criminal_ID_Field.getText());
                pst.setString(2, Decision_Status_Field.getText());
                pst.setString(3, Decision_Section_Of_Law_Field.getText());
                pst.setString(4, Decision_Details_Field.getText());


                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Court Decision Register Successfully");
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }
        
        
        
        
    }//GEN-LAST:event_Decision_Insert_ButtonActionPerformed

    private void Decision_Criminal_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decision_Criminal_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decision_Criminal_ID_FieldActionPerformed

    private void Decision_Section_Of_Law_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decision_Section_Of_Law_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Decision_Section_Of_Law_FieldActionPerformed

    private void Decision_Status_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decision_Status_ComboBoxActionPerformed
        Decision_Status_Field.setText(Decision_Status_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_Decision_Status_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Court_Decision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Decision_Criminal_ID;
    private javax.swing.JTextField Decision_Criminal_ID_Field;
    private javax.swing.JLabel Decision_Details;
    private javax.swing.JTextField Decision_Details_Field;
    private javax.swing.JButton Decision_Insert_Button;
    private javax.swing.JLabel Decision_Section_Of_Law;
    private javax.swing.JTextField Decision_Section_Of_Law_Field;
    private javax.swing.JLabel Decision_Status;
    private javax.swing.JComboBox<String> Decision_Status_ComboBox;
    private javax.swing.JTextField Decision_Status_Field;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
