
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Generate_Forensic_Report extends javax.swing.JFrame {

    /**
     * Creates new form Signup_Page
     */
    public Generate_Forensic_Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Forensic_Report_FIR_ID = new javax.swing.JLabel();
        Forensic_Report_Blood_Group = new javax.swing.JLabel();
        Forensic_Report_Death_Cause = new javax.swing.JLabel();
        Forensic_Report_FIR_ID_Field = new javax.swing.JTextField();
        Forensic_Report_Death_Cause_Field = new javax.swing.JTextField();
        Forensic_Report_Insert_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Forensic_Report_Blood_Group_ComboBox = new javax.swing.JComboBox<>();
        Forensic_Report_Blood_Group_Field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Forensic_Report_FIR_ID.setText("FIR_ID");

        Forensic_Report_Blood_Group.setText("Blood_Group");

        Forensic_Report_Death_Cause.setText("Death_Cause");

        Forensic_Report_FIR_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forensic_Report_FIR_ID_FieldActionPerformed(evt);
            }
        });

        Forensic_Report_Insert_Button.setText("Insert");
        Forensic_Report_Insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forensic_Report_Insert_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORENSIC REPORT FORM");

        Forensic_Report_Blood_Group_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O-Positve", "O-Negative", "A-Positve", "A-Negative", "B-Positive", "B-Negative", "AB-Positive", "AB-Negative" }));
        Forensic_Report_Blood_Group_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forensic_Report_Blood_Group_ComboBoxActionPerformed(evt);
            }
        });

        Forensic_Report_Blood_Group_Field.setEditable(false);
        Forensic_Report_Blood_Group_Field.setText("O-Positive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Forensic_Report_Blood_Group, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Forensic_Report_FIR_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Forensic_Report_Death_Cause, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Forensic_Report_FIR_ID_Field)
                            .addComponent(Forensic_Report_Death_Cause_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(Forensic_Report_Blood_Group_Field))
                        .addGap(18, 18, 18)
                        .addComponent(Forensic_Report_Blood_Group_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Forensic_Report_Insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Forensic_Report_FIR_ID)
                    .addComponent(Forensic_Report_FIR_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Forensic_Report_Blood_Group)
                        .addComponent(Forensic_Report_Blood_Group_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Forensic_Report_Blood_Group_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Forensic_Report_Death_Cause)
                    .addComponent(Forensic_Report_Death_Cause_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Forensic_Report_Insert_Button)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String url="jdbc:sqlserver://localhost:1433;databaseName=CrimeRecordManagementSystem;user=MurtazaDatabase;password=murtaza123";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
    
    private void Forensic_Report_Insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forensic_Report_Insert_ButtonActionPerformed
        try
        {
             
            if(Forensic_Report_Blood_Group_Field.getText().trim().isEmpty() || 
               Forensic_Report_Death_Cause_Field.getText().trim().isEmpty() ||  
               Forensic_Report_FIR_ID_Field.getText().trim().isEmpty() )
            {
                JOptionPane.showMessageDialog(this, "Fields Should Not Be Null");
            }

            else
            {
            
                Class.forName(driver);
                Connection connection= DriverManager.getConnection(url);

                String SQL="insert into Forensic_Report"
                        + "(Fir_id, Blood_group, Cause)"
                        +"values(?, ?, ?)";

                PreparedStatement pst = connection.prepareStatement(SQL);
                pst.setString(1,Forensic_Report_FIR_ID_Field.getText() );
                pst.setString(2, Forensic_Report_Blood_Group_Field.getText());
                pst.setString(3, Forensic_Report_Death_Cause_Field.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Forensic Report Generate Successfully");
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }
        
        
        
        
        
    }//GEN-LAST:event_Forensic_Report_Insert_ButtonActionPerformed

    private void Forensic_Report_FIR_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forensic_Report_FIR_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Forensic_Report_FIR_ID_FieldActionPerformed

    private void Forensic_Report_Blood_Group_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forensic_Report_Blood_Group_ComboBoxActionPerformed
        Forensic_Report_Blood_Group_Field.setText(Forensic_Report_Blood_Group_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_Forensic_Report_Blood_Group_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generate_Forensic_Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Forensic_Report_Blood_Group;
    private javax.swing.JComboBox<String> Forensic_Report_Blood_Group_ComboBox;
    private javax.swing.JTextField Forensic_Report_Blood_Group_Field;
    private javax.swing.JLabel Forensic_Report_Death_Cause;
    private javax.swing.JTextField Forensic_Report_Death_Cause_Field;
    private javax.swing.JLabel Forensic_Report_FIR_ID;
    private javax.swing.JTextField Forensic_Report_FIR_ID_Field;
    private javax.swing.JButton Forensic_Report_Insert_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
