
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Investigation_Officer_Details extends javax.swing.JFrame {

    /**
     * Creates new form Criminal
     */
    public Investigation_Officer_Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inventigation_Officer_ID = new javax.swing.JLabel();
        Inventigation_Officer_Name = new javax.swing.JLabel();
        Inventigation_Officer_City = new javax.swing.JLabel();
        Inventigation_Officer_Phone = new javax.swing.JLabel();
        Inventigation_Officer_State = new javax.swing.JLabel();
        Investigation_Officer_ID_Field = new javax.swing.JTextField();
        Investigation_Officer_Name_Field = new javax.swing.JTextField();
        Investigation_Officer_City_Field = new javax.swing.JTextField();
        Investigation_Officer_Phone_Field = new javax.swing.JTextField();
        Investigation_Officer_State_Field = new javax.swing.JTextField();
        Accused_Insert_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Inventigation_Officer_CNIC = new javax.swing.JLabel();
        Investigation_Officer_CNIC_Field = new javax.swing.JTextField();
        Inventigation_Officer_FIR_ID = new javax.swing.JLabel();
        Investigation_Officer_FIR_ID_Field = new javax.swing.JTextField();
        Inventigation_Officer_Gender = new javax.swing.JLabel();
        Investigation_Officer_Gender_Field = new javax.swing.JTextField();
        Forensic_Officer_Gender_ComboBox = new javax.swing.JComboBox<>();
        Officer_Return_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inventigation_Officer_ID.setText("Officer_ID");

        Inventigation_Officer_Name.setText("Officer_Name");

        Inventigation_Officer_City.setText("City");

        Inventigation_Officer_Phone.setText("Phone");

        Inventigation_Officer_State.setText("State");

        Investigation_Officer_ID_Field.setToolTipText("yyyy-mm-dd");
        Investigation_Officer_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Investigation_Officer_ID_FieldActionPerformed(evt);
            }
        });

        Investigation_Officer_City_Field.setToolTipText("int");
        Investigation_Officer_City_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Investigation_Officer_City_FieldActionPerformed(evt);
            }
        });

        Investigation_Officer_State_Field.setToolTipText("yyyy-mm-dd");
        Investigation_Officer_State_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Investigation_Officer_State_FieldActionPerformed(evt);
            }
        });

        Accused_Insert_Button.setText("Insert");
        Accused_Insert_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accused_Insert_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVESTIGATION OFFICER FORM");

        Inventigation_Officer_CNIC.setText("CNIC");

        Investigation_Officer_CNIC_Field.setToolTipText("yyyy-mm-dd");
        Investigation_Officer_CNIC_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Investigation_Officer_CNIC_FieldActionPerformed(evt);
            }
        });

        Inventigation_Officer_FIR_ID.setText("FIR_ID");

        Investigation_Officer_FIR_ID_Field.setToolTipText("yyyy-mm-dd");
        Investigation_Officer_FIR_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Investigation_Officer_FIR_ID_FieldActionPerformed(evt);
            }
        });

        Inventigation_Officer_Gender.setText("Gender");

        Investigation_Officer_Gender_Field.setEditable(false);
        Investigation_Officer_Gender_Field.setText("Male");
        Investigation_Officer_Gender_Field.setToolTipText("");
        Investigation_Officer_Gender_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Investigation_Officer_Gender_FieldActionPerformed(evt);
            }
        });

        Forensic_Officer_Gender_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Forensic_Officer_Gender_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Forensic_Officer_Gender_ComboBoxActionPerformed(evt);
            }
        });

        Officer_Return_Button.setText("Return");
        Officer_Return_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Officer_Return_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Inventigation_Officer_State, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventigation_Officer_CNIC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventigation_Officer_FIR_ID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventigation_Officer_Gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventigation_Officer_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventigation_Officer_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(Inventigation_Officer_City, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventigation_Officer_Phone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Accused_Insert_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Officer_Return_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Investigation_Officer_Phone_Field)
                    .addComponent(Investigation_Officer_CNIC_Field)
                    .addComponent(Investigation_Officer_Gender_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(Investigation_Officer_Name_Field)
                    .addComponent(Investigation_Officer_City_Field)
                    .addComponent(Investigation_Officer_State_Field)
                    .addComponent(Investigation_Officer_FIR_ID_Field)
                    .addComponent(Investigation_Officer_ID_Field, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(Forensic_Officer_Gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Inventigation_Officer_ID)
                    .addComponent(Investigation_Officer_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Investigation_Officer_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inventigation_Officer_Name, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Investigation_Officer_Gender_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inventigation_Officer_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Forensic_Officer_Gender_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Investigation_Officer_CNIC_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inventigation_Officer_CNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inventigation_Officer_City)
                    .addComponent(Investigation_Officer_City_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inventigation_Officer_Phone)
                    .addComponent(Investigation_Officer_Phone_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inventigation_Officer_State, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Investigation_Officer_State_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inventigation_Officer_FIR_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Investigation_Officer_FIR_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Accused_Insert_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Officer_Return_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String url="jdbc:sqlserver://localhost:1433;databaseName=CrimeRecordManagementSystem;user=MurtazaDatabase;password=murtaza123";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
       
    private void Accused_Insert_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accused_Insert_ButtonActionPerformed
        
        try
        {
            
            if(Investigation_Officer_ID_Field.getText().trim().isEmpty() || 
               Investigation_Officer_State_Field.getText().trim().isEmpty() ||  
               Investigation_Officer_CNIC_Field.getText().trim().isEmpty() || 
               Investigation_Officer_City_Field.getText().trim().isEmpty() ||
               Investigation_Officer_FIR_ID_Field.getText().trim().isEmpty() ||
               Investigation_Officer_Gender_Field.getText().trim().isEmpty() ||
               Investigation_Officer_Name_Field.getText().trim().isEmpty() ||
               Investigation_Officer_Phone_Field.getText().trim().isEmpty() )
            {
                JOptionPane.showMessageDialog(this, "Fields Should Not Be Null");
                
            }

            else
            {
            
                Class.forName(driver);
                Connection connection= DriverManager.getConnection(url);

                String SQL="insert into Investigation_officer"
                        + "(Officer_id, Officer_name, Gender, CNIC, CIty, Officer_ph, State, Fir_id)"
                        +"values(?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement pst = connection.prepareStatement(SQL);

                pst.setString(1, Investigation_Officer_ID_Field.getText());
                pst.setString(2, Investigation_Officer_Name_Field.getText());
                pst.setString(3, Investigation_Officer_Gender_Field.getText());
                pst.setString(4, Investigation_Officer_CNIC_Field.getText());
                pst.setString(5, Investigation_Officer_City_Field.getText());
                pst.setString(6, Investigation_Officer_Phone_Field.getText());
                pst.setString(7, Investigation_Officer_State_Field.getText());
                pst.setString(8, Investigation_Officer_FIR_ID_Field.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Investigation Officer Details Insert Successfully");
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }
        
        
        
        
    }//GEN-LAST:event_Accused_Insert_ButtonActionPerformed

    private void Investigation_Officer_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Investigation_Officer_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_Officer_ID_FieldActionPerformed

    private void Investigation_Officer_State_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Investigation_Officer_State_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_Officer_State_FieldActionPerformed

    private void Investigation_Officer_City_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Investigation_Officer_City_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_Officer_City_FieldActionPerformed

    private void Investigation_Officer_CNIC_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Investigation_Officer_CNIC_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_Officer_CNIC_FieldActionPerformed

    private void Investigation_Officer_FIR_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Investigation_Officer_FIR_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_Officer_FIR_ID_FieldActionPerformed

    private void Investigation_Officer_Gender_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Investigation_Officer_Gender_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Investigation_Officer_Gender_FieldActionPerformed

    private void Forensic_Officer_Gender_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forensic_Officer_Gender_ComboBoxActionPerformed
        Investigation_Officer_Gender_Field.setText(Forensic_Officer_Gender_ComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_Forensic_Officer_Gender_ComboBoxActionPerformed

    private void Officer_Return_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Officer_Return_ButtonActionPerformed
         Main_Page main_page = new Main_Page();
         main_page.setVisible(true);
         
         setVisible(false);
    }//GEN-LAST:event_Officer_Return_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Investigation_Officer_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accused_Insert_Button;
    private javax.swing.JComboBox<String> Forensic_Officer_Gender_ComboBox;
    private javax.swing.JLabel Inventigation_Officer_CNIC;
    private javax.swing.JLabel Inventigation_Officer_City;
    private javax.swing.JLabel Inventigation_Officer_FIR_ID;
    private javax.swing.JLabel Inventigation_Officer_Gender;
    private javax.swing.JLabel Inventigation_Officer_ID;
    private javax.swing.JLabel Inventigation_Officer_Name;
    private javax.swing.JLabel Inventigation_Officer_Phone;
    private javax.swing.JLabel Inventigation_Officer_State;
    private javax.swing.JTextField Investigation_Officer_CNIC_Field;
    private javax.swing.JTextField Investigation_Officer_City_Field;
    private javax.swing.JTextField Investigation_Officer_FIR_ID_Field;
    private javax.swing.JTextField Investigation_Officer_Gender_Field;
    private javax.swing.JTextField Investigation_Officer_ID_Field;
    private javax.swing.JTextField Investigation_Officer_Name_Field;
    private javax.swing.JTextField Investigation_Officer_Phone_Field;
    private javax.swing.JTextField Investigation_Officer_State_Field;
    private javax.swing.JButton Officer_Return_Button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
