/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Main_Page extends javax.swing.JFrame {

    /**
     * Creates new form Main_Page1
     */
    public Main_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Open_Update_Page = new javax.swing.JButton();
        Open_Delete_Page = new javax.swing.JButton();
        Open_Signup_Page = new javax.swing.JButton();
        Open_View_Page = new javax.swing.JButton();
        Open_Fir_Page = new javax.swing.JButton();
        Open_Search_Page = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Open_Update_Page.setText("Update Record");
        Open_Update_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Update_PageActionPerformed(evt);
            }
        });

        Open_Delete_Page.setText("Delete Record");
        Open_Delete_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Delete_PageActionPerformed(evt);
            }
        });

        Open_Signup_Page.setText("Register New User");
        Open_Signup_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Signup_PageActionPerformed(evt);
            }
        });

        Open_View_Page.setText("View All Records");
        Open_View_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_View_PageActionPerformed(evt);
            }
        });

        Open_Fir_Page.setText("New FIR");
        Open_Fir_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Fir_PageActionPerformed(evt);
            }
        });

        Open_Search_Page.setText("Search Record");
        Open_Search_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Search_PageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAIN PAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Open_Fir_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Open_Search_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Open_Update_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Open_Delete_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Open_View_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Open_Signup_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Open_Fir_Page)
                .addGap(18, 18, 18)
                .addComponent(Open_Search_Page)
                .addGap(18, 18, 18)
                .addComponent(Open_Update_Page)
                .addGap(18, 18, 18)
                .addComponent(Open_Delete_Page)
                .addGap(18, 18, 18)
                .addComponent(Open_View_Page)
                .addGap(18, 18, 18)
                .addComponent(Open_Signup_Page)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Open_Delete_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Delete_PageActionPerformed
        
        Delete_Page delete_Page = new Delete_Page();
        delete_Page.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_Open_Delete_PageActionPerformed

    private void Open_Update_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Update_PageActionPerformed
        
        Update_Page update_Page = new Update_Page();
        update_Page.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_Open_Update_PageActionPerformed

    private void Open_Fir_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Fir_PageActionPerformed
        
        Register_FIR FIR = new Register_FIR();
        FIR.setVisible(true);
        
        setVisible(false);
               
    }//GEN-LAST:event_Open_Fir_PageActionPerformed

    private void Open_Signup_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Signup_PageActionPerformed
        
        Signup_Page sign_up = new Signup_Page();
        sign_up.setVisible(true);
        
        setVisible(false);
                
    }//GEN-LAST:event_Open_Signup_PageActionPerformed

    private void Open_Search_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Search_PageActionPerformed
        
        Search_Page search_Page = new Search_Page();
        search_Page.setVisible(true);
        
        setVisible(false);
              
    }//GEN-LAST:event_Open_Search_PageActionPerformed

    private void Open_View_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_View_PageActionPerformed
        
        View_Page view_Page = new View_Page();
        view_Page.setVisible(true);
        
        setVisible(false);
                
    }//GEN-LAST:event_Open_View_PageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Open_Delete_Page;
    private javax.swing.JButton Open_Fir_Page;
    private javax.swing.JButton Open_Search_Page;
    private javax.swing.JButton Open_Signup_Page;
    private javax.swing.JButton Open_Update_Page;
    private javax.swing.JButton Open_View_Page;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
