
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Register_FIR extends javax.swing.JFrame {
int flag=0, alreadyInsert=0;
    /**
     * Creates new form Criminal
     */
    public Register_FIR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FIR_Reg_date = new javax.swing.JLabel();
        FIR_ID = new javax.swing.JLabel();
        Crime_Type = new javax.swing.JLabel();
        Crime_Details = new javax.swing.JLabel();
        Date_of_Crime = new javax.swing.JLabel();
        FIR_Reg_date_Field = new javax.swing.JTextField();
        FIR_ID_Field = new javax.swing.JTextField();
        FIR_Crime_Type_Field = new javax.swing.JTextField();
        FIR_Date_of_Crime_Field = new javax.swing.JTextField();
        FIR_InsertButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Open_Officer_Page = new javax.swing.JButton();
        FIR_Crime_Details_Field = new javax.swing.JTextField();
        FIR_Return_Button1 = new javax.swing.JButton();
        Open_Victim_Page = new javax.swing.JButton();
        Open_Accused_Page = new javax.swing.JButton();
        Open_Crime_Area_Page = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FIR_Reg_date.setText("FIR_Reg_Date");

        FIR_ID.setText("FIR_ID");

        Crime_Type.setText("Crime_Type");

        Crime_Details.setText("Crime_Details");

        Date_of_Crime.setText("Date_of_Crime");

        FIR_Reg_date_Field.setToolTipText("yyyy-mm-dd");
        FIR_Reg_date_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIR_Reg_date_FieldActionPerformed(evt);
            }
        });

        FIR_ID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIR_ID_FieldActionPerformed(evt);
            }
        });

        FIR_Crime_Type_Field.setToolTipText("int");
        FIR_Crime_Type_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIR_Crime_Type_FieldActionPerformed(evt);
            }
        });

        FIR_Date_of_Crime_Field.setToolTipText("yyyy-mm-dd");
        FIR_Date_of_Crime_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIR_Date_of_Crime_FieldActionPerformed(evt);
            }
        });

        FIR_InsertButton.setText("Insert");
        FIR_InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIR_InsertButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FIR REGISTRATION FORM");

        Open_Officer_Page.setText("Assign Case To Officer");
        Open_Officer_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Officer_PageActionPerformed(evt);
            }
        });

        FIR_Return_Button1.setText("Return");
        FIR_Return_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIR_Return_Button1ActionPerformed(evt);
            }
        });

        Open_Victim_Page.setText("Add Victim");
        Open_Victim_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Victim_PageActionPerformed(evt);
            }
        });

        Open_Accused_Page.setText("Add Accused");
        Open_Accused_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Accused_PageActionPerformed(evt);
            }
        });

        Open_Crime_Area_Page.setText("Add Crime Area Details");
        Open_Crime_Area_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Open_Crime_Area_PageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Crime_Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FIR_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FIR_Reg_date)
                            .addComponent(Crime_Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Date_of_Crime))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FIR_Reg_date_Field)
                            .addComponent(FIR_ID_Field)
                            .addComponent(FIR_Crime_Details_Field)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FIR_InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Open_Victim_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FIR_Return_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FIR_Crime_Type_Field)
                            .addComponent(FIR_Date_of_Crime_Field)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Open_Officer_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Open_Accused_Page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Open_Crime_Area_Page, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FIR_Reg_date)
                    .addComponent(FIR_Reg_date_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIR_ID)
                    .addComponent(FIR_ID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crime_Type)
                    .addComponent(FIR_Crime_Type_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crime_Details)
                    .addComponent(FIR_Crime_Details_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date_of_Crime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIR_Date_of_Crime_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIR_InsertButton)
                    .addComponent(FIR_Return_Button1)
                    .addComponent(Open_Victim_Page))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Open_Officer_Page)
                    .addComponent(Open_Accused_Page))
                .addGap(18, 18, 18)
                .addComponent(Open_Crime_Area_Page)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String url="jdbc:sqlserver://localhost:1433;databaseName=CrimeRecordManagementSystem;user=MurtazaDatabase;password=murtaza123";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
       
    private void FIR_InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIR_InsertButtonActionPerformed
        
        try
        {
            if(FIR_Reg_date_Field.getText().trim().isEmpty() || 
               FIR_Crime_Details_Field.getText().trim().isEmpty() ||  
               FIR_Crime_Type_Field.getText().trim().isEmpty() || 
               FIR_Date_of_Crime_Field.getText().trim().isEmpty() ||
               FIR_ID_Field.getText().trim().isEmpty()  )
            {
                JOptionPane.showMessageDialog(this, "Fields Should Not Be Null");
                flag=1;
                alreadyInsert=0;
            }

            else
            {
                flag=0;
                alreadyInsert=1;
        
                Class.forName(driver);
                Connection connection= DriverManager.getConnection(url);

                String SQL="insert into FIR"
                        + "(FIR_Reg_date, Fir_id, Crime_type, Crime_details, Date_of_crime)"
                        +"values(?, ?, ?, ?, ?)";

                PreparedStatement pst = connection.prepareStatement(SQL);

                pst.setString(1, FIR_Reg_date_Field.getText());
                pst.setString(2, FIR_ID_Field.getText());
                pst.setString(3, FIR_Crime_Type_Field.getText());
                pst.setString(4, FIR_Crime_Details_Field.getText());
                pst.setString(5, FIR_Date_of_Crime_Field.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "FIR Register Successfully");
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            flag=1;

        }
        
        
        
        
    }//GEN-LAST:event_FIR_InsertButtonActionPerformed

    private void FIR_Reg_date_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIR_Reg_date_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIR_Reg_date_FieldActionPerformed

    private void FIR_Date_of_Crime_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIR_Date_of_Crime_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIR_Date_of_Crime_FieldActionPerformed

    private void Open_Officer_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Officer_PageActionPerformed
       
      
        if(alreadyInsert==0)
        {
            alreadyInsert=1;
            FIR_InsertButton.doClick();
        }
        
        if(flag==0)
        {
            Investigation_Officer_Details Officer = new Investigation_Officer_Details();
            Officer.setVisible(true);

        }
        
    }//GEN-LAST:event_Open_Officer_PageActionPerformed

    private void FIR_ID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIR_ID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIR_ID_FieldActionPerformed

    private void FIR_Crime_Type_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIR_Crime_Type_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIR_Crime_Type_FieldActionPerformed

    private void FIR_Return_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIR_Return_Button1ActionPerformed
        Main_Page main_page = new Main_Page();
        main_page.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_FIR_Return_Button1ActionPerformed

    private void Open_Victim_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Victim_PageActionPerformed
       
        if(alreadyInsert==0)
        {
            alreadyInsert=1;
            FIR_InsertButton.doClick();
            
        }
        
        if(flag==0)
        {
            Add_Victim victim= new Add_Victim();
            victim.setVisible(true);
        }
    }//GEN-LAST:event_Open_Victim_PageActionPerformed

    private void Open_Accused_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Accused_PageActionPerformed
        
        if(alreadyInsert==0)
        {
            alreadyInsert=1;
            FIR_InsertButton.doClick();
            
        }
        
        if(flag==0)
        {
            Register_Accused accused= new Register_Accused();
            accused.setVisible(true);

        }
    }//GEN-LAST:event_Open_Accused_PageActionPerformed

    private void Open_Crime_Area_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Open_Crime_Area_PageActionPerformed
        
        if(alreadyInsert==0 )
        {
            alreadyInsert=1;
            FIR_InsertButton.doClick();
        }
        
        if(flag==0)
        {
            Crime_Area_Details crime_Area_Details= new Crime_Area_Details();
            crime_Area_Details.setVisible(true);

        }
    }//GEN-LAST:event_Open_Crime_Area_PageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_FIR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Crime_Details;
    private javax.swing.JLabel Crime_Type;
    private javax.swing.JLabel Date_of_Crime;
    private javax.swing.JTextField FIR_Crime_Details_Field;
    private javax.swing.JTextField FIR_Crime_Type_Field;
    private javax.swing.JTextField FIR_Date_of_Crime_Field;
    private javax.swing.JLabel FIR_ID;
    private javax.swing.JTextField FIR_ID_Field;
    private javax.swing.JButton FIR_InsertButton;
    private javax.swing.JLabel FIR_Reg_date;
    private javax.swing.JTextField FIR_Reg_date_Field;
    private javax.swing.JButton FIR_Return_Button1;
    private javax.swing.JButton Open_Accused_Page;
    private javax.swing.JButton Open_Crime_Area_Page;
    private javax.swing.JButton Open_Officer_Page;
    private javax.swing.JButton Open_Victim_Page;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
