
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author OWNER
 */
public class Register_Criminal extends javax.swing.JFrame {

    /**
     * Creates new form Criminal
     */
    public Register_Criminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CriminalId = new javax.swing.JLabel();
        CriminalName = new javax.swing.JLabel();
        CriminalIdentification = new javax.swing.JLabel();
        CriminalGender = new javax.swing.JLabel();
        CriminalFirID = new javax.swing.JLabel();
        CriminalIDField = new javax.swing.JTextField();
        CriminalNameField = new javax.swing.JTextField();
        CriminalIdetificationField = new javax.swing.JTextField();
        CriminalGenderField = new javax.swing.JTextField();
        CriminalFirIdField = new javax.swing.JTextField();
        CriminalInsertButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        CriminalId.setText("Criminal_ID");

        CriminalName.setText("Criminal_Name");

        CriminalIdentification.setText("Criminal_Identification");

        CriminalGender.setText("Gender");

        CriminalFirID.setText("Fir_ID");

        CriminalIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriminalIDFieldActionPerformed(evt);
            }
        });

        CriminalGenderField.setEditable(false);
        CriminalGenderField.setText("Male");
        CriminalGenderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriminalGenderFieldActionPerformed(evt);
            }
        });

        CriminalInsertButton.setText("Insert");
        CriminalInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriminalInsertButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRIMINAL REGISTRATION FORM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(CriminalInsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CriminalId)
                            .addComponent(CriminalName)
                            .addComponent(CriminalIdentification)
                            .addComponent(CriminalGender)
                            .addComponent(CriminalFirID))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CriminalGenderField)
                            .addComponent(CriminalIDField)
                            .addComponent(CriminalNameField)
                            .addComponent(CriminalIdetificationField)
                            .addComponent(CriminalFirIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CriminalId)
                    .addComponent(CriminalIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriminalName)
                    .addComponent(CriminalNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriminalIdentification)
                    .addComponent(CriminalIdetificationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriminalGender)
                    .addComponent(CriminalGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriminalFirID, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CriminalFirIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CriminalInsertButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String url="jdbc:sqlserver://localhost:1433;databaseName=CrimeRecordManagementSystem;user=MurtazaDatabase;password=murtaza123";
    String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
     
    
    private void CriminalInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriminalInsertButtonActionPerformed
        
        if(CriminalIDField.getText().trim().isEmpty() || 
           CriminalFirID.getText().trim().isEmpty() ||  
           CriminalIdetificationField.getText().trim().isEmpty() || 
           CriminalNameField.getText().trim().isEmpty()     )
        {
            JOptionPane.showMessageDialog(this, "Fields Should Not Be Null");
        }
        
        else
        {
            try
            {
                Class.forName(driver);
                Connection connection= DriverManager.getConnection(url);

                String SQL="insert into Criminal"
                        + "(Name, Criminal_Id, Criminal_identification, Gender, Fir_id)"
                        +"values(?, ?, ?, ?, ?)";

                PreparedStatement pst = connection.prepareStatement(SQL);
                pst.setString(2,CriminalIDField.getText() );
                pst.setString(1, CriminalNameField.getText());
                pst.setString(3, CriminalIdetificationField.getText());
                pst.setString(4, CriminalGenderField.getText());
                pst.setString(5, CriminalFirIdField.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Criminal Record Insert Successfully");

            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());

            }
        }
        
        
        
        
    }//GEN-LAST:event_CriminalInsertButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       CriminalGenderField.setText(jComboBox1.getSelectedItem().toString());
       
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CriminalGenderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriminalGenderFieldActionPerformed
       
    }//GEN-LAST:event_CriminalGenderFieldActionPerformed

    private void CriminalIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriminalIDFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CriminalIDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Criminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CriminalFirID;
    private javax.swing.JTextField CriminalFirIdField;
    private javax.swing.JLabel CriminalGender;
    private javax.swing.JTextField CriminalGenderField;
    private javax.swing.JTextField CriminalIDField;
    private javax.swing.JLabel CriminalId;
    private javax.swing.JLabel CriminalIdentification;
    private javax.swing.JTextField CriminalIdetificationField;
    private javax.swing.JButton CriminalInsertButton;
    private javax.swing.JLabel CriminalName;
    private javax.swing.JTextField CriminalNameField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
